### ISSUE TITLE
Wrong process in armgcc linker flags

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/cbuild#27]
If we have yml linker like
```yaml
      Link:
      - "-mcpu=cortex-m4"
      - "-Wall"
      - "-mfloat-abi=hard"
      - "-mfpu=fpv4-sp-d16"
      - "--specs=nano.specs"
      - "--specs=nosys.specs"
      - "-fno-common"
      - "-ffunction-sections"
      - "-fdata-sections"
      - "-ffreestanding"
      - "-fno-builtin"
      - "-mthumb"
      - "-mapcs"
      - "-Xlinker --gc-sections"
      - "-Xlinker -static"
      - "-Xlinker -z"
      - "-Xlinker muldefs"
      - "-Xlinker -Map=output.map"
      - "-Wl,--print-memory-usage"
```

In the output hello_world.debug+armgcc.cprj, we have
```xml
    <ldflags add="-g -mcpu=cortex-m4 -Wall -mfloat-abi=hard -mfpu=fpv4-sp-d16 --specs=nano.specs --specs=nosys.specs -fno-common -ffunction-sections -fdata-sections -ffreestanding -fno-builtin -mthumb -mapcs -Xlinker --gc-sections -Xlinker -static -Xlinker -z -Xlinker muldefs -Xlinker -Map=output.map -Wl,--print-memory-usage" compiler="GCC" file="./armgcc/MK64FN1M0xxx12_flash.ld"/>
```

In the generated cmakelist, we have
```
set(LD_FLAGS_GLOBAL "-g -mcpu=cortex-m4 -Wall -mfloat-abi=hard -mfpu=fpv4-sp-d16 --specs=nano.specs --specs=nosys.specs -fno-common -ffunction-sections -fdata-sections -ffreestanding -fno-builtin -mthumb -mapcs -Xlinker --gc-sections -static -z -Xlinker muldefs -Map=output.map -Wl,--print-memory-usage")
```

Note the xlinker part, it is wrong, seems the cbuild.sh does a merge, but not correct, it will result 
arm-none-eabi-gcc.exe: error: muldefs: No such file or directory
arm-none-eabi-gcc.exe: error: unrecognized command-line option '-Map=output.map'
ninja: build stopped: subcommand failed.

It should be like 
set(LD_FLAGS_GLOBAL "-g -mcpu=cortex-m4 -Wall -mfloat-abi=hard -mfpu=fpv4-sp-d16 --specs=nano.specs --specs=nosys.specs -fno-common -ffunction-sections -fdata-sections -ffreestanding -fno-builtin -mthumb -mapcs -Xlinker --gc-sections -Xlinker -static -Xlinker -z -Xlinker muldefs -Xlinker -Map=output.map  -Wl,--print-memory-usage")

**Comment by brondani** [comment]
This is not an issue in the [YML-Input-Format](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#misc) because the options are separated in different YML nodes, but `ldflags` in CPRJ is a list of `" -"` separated options. A proper fix to the issue described here would ideally require changing the CPRJ specification to clearly differentiate tokens. Since CPRJ is being deprecated I would advise against any further action on this matter.

@tcsunhao Please confirm whether using `-Wl,` instead of `-Xlinker ` or adding `-Xlinker` arguments between quotation marks are valid workarounds.

For example:
```
  Link:
    - -Wl,--gc-sections
    - -Wl,-static
    - -Wl,-z
    - -Wl,muldefs
    - -Wl,-Map=output.map
```
```
  Link:
    - -Xlinker "--gc-sections"
    - -Xlinker "-static"
    - -Xlinker "-z"
    - -Xlinker "muldefs"
    - -Xlinker "-Map=output.map"
```

**Comment by tcsunhao** [comment]
Hi @jkrech, about your first question. Theoretically, if a compiler/linker flags are supported by compiler/linker set, then NXP SDK data model and generator needs to support it. Specifically, to xlinker and wl, some developers may like xlinker, some may like wl.  It depends on NXP SDK developers. 

For 'mpu', 'endian=little' such chip arch related options, yes, you are right, we can leave it to cproject/csolution 'device' data and your tool engine to achieve it. Just that these data are already in our data. For IAR, duplicated 'mpu' options will result build failed. For MDK,armgcc, seems not.

About --specs, they have already been put into NXP data for all devices.

**Comment by tcsunhao** [comment]
Hi @brondani, thanks for your quick comment. Your 2 suggestions can both work. 

However, if you look at the armgcc spec
![image](https://user-images.githubusercontent.com/3381677/205805025-366d2f43-8444-465f-8009-ee182c21664c.png)
Existing NXP way of "-Xlinker -Map=output.map" exactly follows the spec. We can image that many embedded developers may use this way in their daily work with armgcc. They will meet the same issue.
Thanks for reminder that cprj has been deprecated(I ignore it), but anyway the generated cmakelist is not with expected compiler flag data which result in build failure.

**Comment by jkrech** [comment]
In CMSIS-Toolbox 2.0.0 the cprj is still the format for creating reproducible builds.

**Comment by brondani** [comment]
This is supported in `cbuild2cmake` and covered by tests since https://github.com/Open-CMSIS-Pack/cbuild2cmake/pull/84
