### ISSUE TITLE
ld file change not detected ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/cbuild#4]
First of all, I must say thatI worked with:
> cbuild.sh --version
(cbuild.sh): Build Invocation 0.10.6 (C) 2021 ARM

But here is what I observed:
- generate a project
- compile it

Then, in the RTE folder, update manually your ld file.

Then:
> cbuild.sh gpio-toggle.GCC+B-U585I-IOT02A.cprj
(cbuild.sh): Build Invocation 0.10.6 (C) 2021 ARM
gpio-toggle.GCC+B-U585I-IOT02A.cprj validates
(cbuildgen): Build Process Manager 0.10.6 (C) 2022 ARM
M650: Command completed successfully.
(cbuildgen): Build Process Manager 0.10.6 (C) 2022 ARM
M652: Generated file for project build: 'C:/Cube/stm32cube_fw_all/examples/hal/gpio/toggle/projects/gpio-toggle.GCC+B-U585I-IOT02A_IntDir/CMakeLists.txt'
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Cube/stm32cube_fw_all/examples/hal/gpio/toggle/projects/gpio-toggle.GCC+B-U585I-IOT02A_IntDir
ninja: no work to do.
cbuild.sh finished successfully!

I assume the same problem exists with the exe version of cbuild.

I would expect "cbuild"  to detect that the content of my RTE folder has evolved since the last build.

**Comment by fred-r** [comment]
Reproduced with exe version as well:

> cbuild.exe gpio-toggle.GCC+B-U585I-IOT02A.cprj
info cbuild: cbuild: Build Invocation 0.9.0 (C) 2022 ARM
(cbuildgen): Build Process Manager 0.11.0 (C) 2022 ARM
M650: Command completed successfully.
(cbuildgen): Build Process Manager 0.11.0 (C) 2022 ARM
M652: Generated file for project build: 'C:/Cube20/stm32cube_fw_all/examples/hal/gpio/toggle/projects/gpio-toggle.GCC+B-U585I-IOT02A_IntDir/CMakeLists.txt'
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Cube20/stm32cube_fw_all/examples/hal/gpio/toggle/projects/gpio-toggle.GCC+B-U585I-IOT02A_IntDir
ninja: no work to do.
info cbuild: build finished successfully!

**Comment by brondani** [comment]
Hi @fred-r, thanks for reporting this.
`cbuild` does not handle dependencies, this is under `CMake` responsibility.
The linker script is not automatically handled by CMake as a dependency. It should be explicitly added into the generated CMakeLists.
This change would need to be done in the CMakeLists generation in the `devtools/cbuildgen` application.

**Comment by jeromecoutant** [comment]
Hi
Should we open a new issue in devtools, or it is already in the todo list ? :-)
Thx

**Comment by brondani** [comment]
> Should we open a new issue in devtools, or it is already in the todo list ?

The `devtools` would be more appropriate in this case, but it is already in the todo list, no further action is needed on the issue management side.

**Comment by brondani** [comment]
@fred-r Can you please test it with the latest CMSIS-Toolbox 1.1.0? Many thanks!
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/tag/1.1.0

**Comment by jkrech** [comment]
Dependency on linker script file changes added to 1.1.0 already. No confirmation received from user after many months. Closing.
