### ISSUE TITLE
[cbuild] doesn't report build status properly via exit code

### ISSUE THREAD

**Issue by JonatanAntoni** [Open-CMSIS-Pack/cbuild#48]
Using `cbuild` to build a solution context which has compiler issues still returns with error level 0:
```
$ cbuild demo.csolution.yml --context demo.debug+target --packs --update-rte
info cbuild: Build Invocation 1.5.0 (C) 2023 Arm Ltd. and Contributors
 :
ninja: build stopped: subcommand failed.
error cbuild: error executing 'cmake' build
error cbuild: error building './demo.debug+target.cprj'

$ echo "cbuild returned with exit code $?"
cbuild returned with exit code 0
                                ^
                                this should reflect the error 
```

Instead, `cbuild` should report the overall result in its exit code.

**Comment by soumeh01** [comment]
I could replicate the issue `cbuild 1.5.0`.
Seems like this issue is resolved in the cleanup and restructuring. Couldn't replicate in the current binaries.
https://github.com/Open-CMSIS-Pack/cbuild/actions/runs/4365909868

**Comment by jkrech** [comment]
@JonatanAntoni I am closing this now, but please reopen in case you find it is not solved for you.
