### ISSUE TITLE
RTE device update not detected ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/cbuild#5]
I fixed a board definition issue and regenerated the project with csolution:

```
|   |-- RTE
|   |   |-- Device
|   |   |   |-- STM32U585AIIx
|   |   |   |   |-- STM32U585xx_FLASH.ld
|   |   |   |   |-- stm32_external_env.h
|   |   |   |   |-- stm32_external_env.h@0.0.1
|   |   |   |   |-- stm32u585xx_flash.icf
|   |   |   |   |-- stm32u585xx_flash.sct
|   |   |   |   |-- system_stm32u5xx.c
|   |   |   |   `-- system_stm32u5xx.c@0.0.1
|   |   |   `-- STM32U585ZITx
|   |   |       |-- STM32U585xx_FLASH.ld
|   |   |       |-- stm32_external_env.h
|   |   |       |-- stm32u585xx_flash.icf
|   |   |       |-- stm32u585xx_flash.icf@0.0.1
|   |   |       |-- stm32u585xx_flash.sct
|   |   |       `-- system_stm32u5xx.c

```

I did not erase the U585ZITxxx device but now I have the proper device next to it: U585AIIx.

But nothing gets built:
```
> cbuild.exe -c gpio-toggle.GCC+B-U585I-IOT02A.cprj
info cbuild: cbuild: Build Invocation 0.9.1 (C) 2022 ARM
info cbuild: finished successfully!
```

**Comment by jkrech** [comment]
@fred-r since you have specified `-c` for cleaning, all this command will do is removing the intermediate and output directories:
```
Flags:
  -c, --clean              Remove intermediate and output directories
```
I guess your expectation is that the command would first clean and then rebuild the project.
Please confirm that once you specify the above command without `-c` that you see the project being built.

**Comment by fred-r** [comment]
Same effect without -c

**Comment by fred-r** [comment]
Besides, to me, I should be able to ask for a "clean build" with -c in addition to the build request.

So -c alone = build
-c +,context = clean & build

**Comment by jkrech** [comment]
@fred-r , could you specify the `-d` option so we get a bit more output what is being executed?

**Comment by fred-r** [comment]
Ah, I cleaned up my example...I will set it up again :-)

**Comment by brondani** [comment]
@fred-r Please note there is no "context" nor "clean build" options for **cbuild**:
```
$ ./cbuild -h
cbuild: Build Invocation 0.9.1 (C) 2022 ARM

Usage:
  cbuild <project.cprj> [flags]

Flags:
  -c, --clean              Remove intermediate and output directories
  -d, --debug              Enable debug messages
  -g, --generator string   Select build system generator (default "Ninja")
  -h, --help               Print usage
  -i, --intdir string      Set intermediate directory
  -j, --jobs int           Number of job slots for parallel execution
  -l, --log string         Save output messages in a log file
  -o, --outdir string      Set output directory
  -q, --quiet              Suppress output messages except build invocations
  -s, --schema             Check *.cprj file against CPRJ.xsd schema
  -t, --target string      Optional CMake target name
  -u, --update string      Generate cprj file for reproducing current build
  -v, --version            Print version
```
For a "clean build" you should first clean and then build:
```
cbuild MyProject.cprj --clean
cbuild MyProject.cprj
```

**Comment by brondani** [comment]
@fred-r We have added the `cbuild` option `-r, --rebuild`, can you please test it with the latest CMSIS-Toolbox 1.1.0? Thanks!
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/tag/1.1.0

**Comment by jkrech** [comment]
Feature was added using rebuild. No response from reporter in a long time.
