### ISSUE TITLE
toolchain registration improvement: ignore version info

### ISSUE THREAD

**Issue by Hoohaha** [Open-CMSIS-Pack/cbuild#54]
Hi,

Currently the toolchain registration need to set with below format:
TOOLCHAIN=<path/to/toolchain/binaries>

Can we use format like {name}_TOOLCHAIN to ignore the version?
in this way, it makes easy to configure

or use an command line option?
Now it is hard to use, because i do not know what version numbers I should set!

**Comment by jkrech** [comment]
I guess you are referring to this description:
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/installation.md#toolchain-registration

Unfortunately it is essential for the tools to know about the specified toolchain version.
You should be able to identify the version of the toolchain before setting an environment variable.

```
arm-none-eabi-gcc --dumpversion
```

**Comment by jkrech** [comment]
A) If you have multiple versions of a compiler installed on your machine, you can register them all using environment variables.
B) You can specify a version or minVersion of the compiler to be used in the yaml input file. See:
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#compiler
C) You can specify a version of the compiler from the command line: `cbuild mysolution.csolution.yml --toolchain AC6@6.20.0`
D) You can list all registered compiler versions: `cbuild list toolchains`

**Comment by jkrech** [comment]
One thing that was not mentioned above is that you can put a toolchain (e.g. armclang) in the $PATH and rely on CMake to locate and identify the toolchain.
